package com.android.gamerenter

const val FIRESTORE_COLLECTION_UPCOMING = "UPCOMING_GAMES"
const val FIRESTORE_COLLECTION_RENTED = "RENTED_GAMES"
const val FIRESTORE_COLLECTION_ALL = "SEARCH_GAMES"
const val FIRESTORE_COLLECTION_PLATFORM = "PLATFORM_GAMES"