package com.android.gamerenter

const val FIRESTORE_COLLECTION_UPCOMING = "UPCOMING_GAMES"
const val FIRESTORE_COLLECTION_RENTED = "RENTED_GAMES"
const val FIRESTORE_COLLECTION_RECENT_SEARCH = "RECENT_SEARCH_GAMES"
const val FIRESTORE_COLLECTION_ALL = "SEARCH_GAMES"
const val FIRESTORE_COLLECTION_PLATFORM = "PLATFORM_GAMES"

const val FIREBASE_STORAGE_GAMES_ROOT = "GAMES"

const val FIREBASE_STORAGE_LOCATION = "gs://gamerenter-6fa4b.appspot.com/"